### ISSUE TITLE
How to specify link function

### ISSUE THREAD

**Issue by harrelfe** [ntjames/bayesCPM#1]
Nathan how do you specify the link function?

In the example the link was not specified and the comment says the probit link is being used.  Is that correct?

On an unrelated note: 
* How do you suppress the sampling messages?
* How do you save the compiled stan object for re-use with bayes_cpm?
* Think about adding this to the example:

```
options(mc.cores = parallel::detectCores())
# To avoid recompilation of unchanged Stan programs:
rstan::rstan_options(auto_write = TRUE)

w <- fit_cdf
ggplot(w, aes(x=yval, y=med_cdf, color=as.factor(x1))) + geom_step() +
	geom_ribbon(aes(ymin=cdf_q10, ymax=cdf_q90), linetype=0, alpha=0.2) +
	guides(color=guide_legend(title='x1')) +
	xlab('y') + ylab('Posterior Median CDF')
# Would be nice if could specify step functions for geom_ribbon

```

**Comment by ntjames** [comment]
The link function is currently specified using the `link=` argument in the `mkStanDat()` function (1 = logistic, 2 = probit, 3 = loglog, 4 = cloglog, 5 = cauchit; currently there may be some issues with the non-symmetric links). When I implement the formula interface, the `mkStanDat()` will be moved behind-the-scenes and the link will be specified similar to `orm()`, e.g. `bayes_cpm(y~x1, link=logistic)` 

For your other questions:

1) You can suppress sampling progress messages using the `refresh=` argument
 
```fit <- bayes_cpm(dat_stan, refresh=0)```

2) The compiled model can be accessed from the stanfit object, then used with `sampling()` and new data. Note that the new fit is _not_ an update of the original fit.

```
fit <- bayes_cpm(dat_stan)  
compiled_mod <- fit@stanmodel  
fit2 <- rstan::sampling(compiled_mod, new_dat_stan)  
```

3) I can add credible intervals to the cdf in the example. There is a `geom_stepribbon()` but it's not implemented in the main ggplot2 library. I wanted to avoid a lot of package dependencies in the example

**Comment by ntjames** [comment]
Updated package to use formula interface and added credible intervals in README
